apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: horsetraining
resources:
  - namespace.yaml
  - web/deployment.yaml
  - web/service.yaml
  - cloudflared/service-account.yaml
  - cloudflared/configmap.yaml
  - cloudflared/deployment.yaml
